### ISSUE TITLE
wssip installation error. 

### ISSUE THREAD

**Issue by susantaroy2002** [nccgroup/wssip#5]
## Issue:

I am getting below error while installing the wssip. 
Please suggest on this. 

sh: 1: node: not found
npm ERR! Linux 4.10.0-28-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "i" "-g" "electron@1.7"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! electron@1.7.6 postinstall: `node install.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the electron@1.7.6 postinstall script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the electron package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electron
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls electron
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/sr/Desktop/wssip/npm-debug.log

## logs:

[npm-debug.log.tar.gz](https://github.com/nccgroup/wssip/files/1284309/npm-debug.log.tar.gz)

**Comment by thekettu** [comment]
Unfortunately that is an electron-specific bug and not a wssip one. I have also updated the README to phase out installing electron globally and generally recommend `npx wssip` now.
